//
// Created by serge on 24.09.2022.
//

#ifndef INC_37_2_CONNECTING_INTERFACES_TO_THE_APPLICATION_SIMPLEPHONEMAINWINDOW_H
#define INC_37_2_CONNECTING_INTERFACES_TO_THE_APPLICATION_SIMPLEPHONEMAINWINDOW_H

#endif //INC_37_2_CONNECTING_INTERFACES_TO_THE_APPLICATION_SIMPLEPHONEMAINWINDOW_H
